/*
 * Copyright 2026 Snowplow Analytics Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.snowplowanalytics.cdc.scaffold

import com.snowplowanalytics.cdc.pg.DbMetadata
import com.snowplowanalytics.cdc.pg.TableMetadata
import com.snowplowanalytics.cdc.util.slugify

/**
 * Renders a starter config.yaml — a valid instance of the existing config grammar (no new keys).
 * Hand-templated so header and TODO comments survive (Jackson YAML cannot emit comments).
 */
object ConfigYamlGenerator {
    fun generate(md: DbMetadata, vendor: String, coords: ScaffoldConnectionCoords): String {
        val sb = StringBuilder()
        sb.appendLine("# ============================================================================")
        sb.appendLine("# AUTO-GENERATED by cdc-service scaffold — review before deploying to production.")
        sb.appendLine("# auto-generated starting point: column lists carry no transforms or renames, and")
        sb.appendLine("# generated Iglu schemas have no business constraints. Edit to match your")
        sb.appendLine("# tracking plan.")
        sb.appendLine("#")
        sb.appendLine("# Any value below may be replaced with \${ENV_VAR} interpolation (e.g. to keep")
        sb.appendLine("# the hostname or database out of source control). The password is already")
        sb.appendLine("# templated as \${POSTGRES_PASSWORD}; set that env var before running the service.")
        sb.appendLine("# ============================================================================")
        sb.appendLine("# yaml-language-server: \$schema=./cdc-service-config.schema.json")
        sb.appendLine()
        sb.appendLine("service:")
        sb.appendLine("  app_id: ${slugify(coords.database)}-cdc")
        sb.appendLine()
        sb.appendLine("source:")
        sb.appendLine("  connector: postgres")
        sb.appendLine("  hostname: ${coords.hostname}")
        sb.appendLine("  port: ${coords.port}")
        sb.appendLine("  database: ${coords.database}")
        sb.appendLine("  username: ${coords.username}")
        sb.appendLine("  password: \${POSTGRES_PASSWORD}")
        sb.appendLine("  slot_name: snowplow_cdc")
        sb.appendLine("  publication_name: snowplow_cdc_pub")
        sb.appendLine()
        sb.appendLine("debezium:")
        sb.appendLine("  snapshot_mode: never")
        sb.appendLine("  offset_store:")
        sb.appendLine("    type: file")
        sb.appendLine("    file_path: /var/lib/cdc/offsets.dat")
        sb.appendLine("  heartbeat_interval_ms: 30000")
        sb.appendLine("  publication_autocreate_mode: filtered")
        sb.appendLine("  provide_transaction_metadata: false")
        sb.appendLine()
        sb.appendLine("snowplow:")
        sb.appendLine("  collector_url: \${COLLECTOR_URL}")
        sb.appendLine("  cdc_source_schema: iglu:com.snowplowanalytics/cdc_source/jsonschema/1-0-0")
        sb.appendLine("  emitter:")
        sb.appendLine("    batch_size: 50")
        sb.appendLine("    buffer_capacity: 1000")
        sb.appendLine()
        sb.appendLine("tables:")
        md.tables.forEach { appendTable(sb, it, vendor) }
        sb.appendLine()
        sb.appendLine("observability:")
        sb.appendLine("  http:")
        sb.appendLine("    port: 8080")
        sb.appendLine("  heartbeat:")
        sb.appendLine("    interval_ms: 60000")
        return sb.toString()
    }

    private fun appendTable(sb: StringBuilder, t: TableMetadata, vendor: String) {
        sb.appendLine("  - name: ${t.key.name}")
        sb.appendLine("    schema: ${t.key.schema}")
        sb.appendLine("    iglu_schema: iglu:$vendor/${t.key.name}_change/jsonschema/1-0-0")
        if (t.primaryKeyColumns.isNotEmpty()) {
            sb.appendLine("    primary_key: [${t.primaryKeyColumns.joinToString(", ")}]")
        } else {
            val hint = if (t.uniqueIndexes.isNotEmpty()) {
                " Candidate unique index(es): ${t.uniqueIndexes.joinToString("; ") { "(${it.joinToString(", ")})" }}."
            } else " No unique index found; add a surrogate key or exclude this table."
            sb.appendLine("    # TODO: ${t.key} has no PRIMARY KEY. Set the column(s) that uniquely")
            sb.appendLine("    #       identify a row — these feed the deterministic event_id used for")
            sb.appendLine("    #       replay dedupe. The service refuses to start until this is set.$hint")
            sb.appendLine("    primary_key: []")
        }
        sb.appendLine("    columns:")
        t.columns.forEach { sb.appendLine("      - ${it.name}") }
    }
}
